language: cpp
compiler:
  - gcc
  - clang
before_install :
  - sudo apt-get install libboost-dev libboost-python-dev
# Change this to your needs..
script: cmake . -DWITH_BOOST=TRUE  && make && make test