language: cpp
compiler:
  - gcc
  - clang
#before_install :
#  - sudo apt-cache search libboost
#  - sudo apt-get install libboost1.49-dev libboost-python1.49-dev
# Change this to your needs..
script: cmake . && externalLibs && cmake . -DWITH_TRWS=TRUE  && make && make test